import { BadRequestException, Injectable } from '@nestjs/common';
import { KycStatus, Prisma, RiskAlertStatus, Role, TransferStatus } from '../prisma';
import { DatabaseService } from '../database.service';
import { AuditService } from '../audit/audit.service';
import { EncryptionService } from '../security/encryption.service';
import { SupportService } from '../support/support.service';
import { CreateMessageDto } from '../support/support.dto';
import { AssignRoleDto, CreateFeeDto, ReviewKycDto, SetConfigDto, UpdateRiskAlertDto, UpdateTicketDto } from './admin.dto';
import { LedgerService } from '../ledger/ledger.service';

@Injectable()
export class AdminService {
  constructor(private readonly db: DatabaseService, private readonly audit: AuditService, private readonly encryption: EncryptionService, private readonly support: SupportService, private readonly ledger: LedgerService) {}
  customers(search?: string) { return this.db.user.findMany({ where: search ? { OR: [{ email: { contains: search, mode: 'insensitive' } }, { firstName: { contains: search, mode: 'insensitive' } }, { lastName: { contains: search, mode: 'insensitive' } }] } : {}, select: { id: true, email: true, phone: true, firstName: true, lastName: true, status: true, emailVerifiedAt: true, phoneVerifiedAt: true, createdAt: true, kycProfile: { select: { status: true, riskLevel: true } }, _count: { select: { accounts: true, cards: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); }
  async customer(id: string) { const customer = await this.db.user.findUniqueOrThrow({ where: { id }, include: { roles: true, kycProfile: { include: { documents: true } }, accounts: { select: { id: true, name: true, type: true, status: true, currency: true, accountNumberLast4: true, openedAt: true } }, devices: true } }); const balances = await this.ledger.balances(customer.accounts.map((account) => account.id)); return { ...customer, accounts: customer.accounts.map((account) => { const balance = balances.get(account.id)!; return { ...account, ledgerBalance: balance.ledgerBalance.toFixed(2), availableBalance: balance.availableBalance.toFixed(2), activeHolds: balance.activeHolds.toFixed(2) }; }) }; }
  async assignRole(actorId: string, userId: string, dto: AssignRoleDto) { const role = await this.db.userRole.upsert({ where: { userId_role: { userId, role: dto.role } }, create: { userId, role: dto.role }, update: {} }); await this.audit.record({ actorUserId: actorId, action: 'admin.role.assigned', entityType: 'user', entityId: userId, metadata: { role: dto.role } }); return role; }
  kycQueue() { return this.db.kycProfile.findMany({ where: { status: { in: [KycStatus.SUBMITTED, KycStatus.IN_REVIEW] } }, include: { user: { select: { id: true, email: true, firstName: true, lastName: true } }, documents: true }, orderBy: { submittedAt: 'asc' } }); }
  async reviewKyc(actorId: string, id: string, dto: ReviewKycDto) { if (!new Set<KycStatus>([KycStatus.APPROVED, KycStatus.REJECTED]).has(dto.decision)) throw new BadRequestException('Decision must be approved or rejected'); const profile = await this.db.kycProfile.update({ where: { id }, data: { status: dto.decision, riskLevel: dto.riskLevel, rejectionReason: dto.decision === KycStatus.REJECTED ? dto.reason : null, reviewedById: actorId, reviewedAt: new Date() } }); await this.audit.record({ actorUserId: actorId, action: `admin.kyc.${dto.decision.toLowerCase()}`, entityType: 'kyc_profile', entityId: id, metadata: { reason: dto.reason, riskLevel: dto.riskLevel } }); return profile; }
  transactions() { return this.db.transaction.findMany({ include: { account: { select: { userId: true, accountNumberLast4: true } } }, orderBy: { createdAt: 'desc' }, take: 200 }); }
  transfers(status?: TransferStatus) { return this.db.transfer.findMany({ where: status ? { status } : {}, include: { fromAccount: { select: { userId: true, accountNumberLast4: true } }, beneficiary: { select: { legalName: true, bankName: true } }, events: { orderBy: { createdAt: 'asc' } } }, orderBy: { createdAt: 'desc' }, take: 200 }); }
  async approveTransfer(actorId: string, id: string) { const transfer = await this.db.transfer.update({ where: { id }, data: { approvedById: actorId, approvedAt: new Date() } }); await this.db.transferEvent.create({ data: { transferId: id, toStatus: transfer.status, actorUserId: actorId, reason: 'Operations approval granted; queued for execution' } }); await this.db.riskAlert.updateMany({ where: { transferId: id, status: { in: [RiskAlertStatus.OPEN, RiskAlertStatus.INVESTIGATING] } }, data: { status: RiskAlertStatus.CLEARED, resolvedAt: new Date(), assignedToId: actorId } }); await this.audit.record({ actorUserId: actorId, action: 'admin.transfer.approved', entityType: 'transfer', entityId: id }); return transfer; }
  alerts() { return this.db.riskAlert.findMany({ include: { customer: { select: { email: true, firstName: true, lastName: true } } }, orderBy: [{ status: 'asc' }, { createdAt: 'desc' }], take: 200 }); }
  updateAlert(actorId: string, id: string, dto: UpdateRiskAlertDto) { return this.db.riskAlert.update({ where: { id }, data: { status: dto.status, assignedToId: dto.assignedToId ?? actorId, resolvedAt: new Set<RiskAlertStatus>([RiskAlertStatus.CLEARED, RiskAlertStatus.BLOCKED]).has(dto.status) ? new Date() : null } }); }
  cards() { return this.db.card.findMany({ include: { user: { select: { email: true, firstName: true, lastName: true } }, account: { select: { accountNumberLast4: true } } }, orderBy: { createdAt: 'desc' }, take: 200 }); }
  tickets() { return this.db.supportTicket.findMany({ include: { customer: { select: { email: true, firstName: true, lastName: true } }, assignedTo: { select: { email: true } }, _count: { select: { messages: true } } }, orderBy: { updatedAt: 'desc' }, take: 200 }); }
  updateTicket(id: string, dto: UpdateTicketDto) { return this.db.supportTicket.update({ where: { id }, data: { assignedToId: dto.assignedToId, status: dto.status } }); }
  replyTicket(actorId: string, id: string, dto: CreateMessageDto) { return this.support.message(actorId, id, dto, true); }
  fees() { return this.db.feeSchedule.findMany({ orderBy: { activeFrom: 'desc' } }); }
  createFee(actorId: string, dto: CreateFeeDto) { return this.db.feeSchedule.create({ data: { transferType: dto.transferType, currency: dto.currency.toUpperCase(), fixedAmount: new Prisma.Decimal(dto.fixedAmount), percentage: new Prisma.Decimal(dto.percentage), activeFrom: new Date() } }).then(async (fee) => { await this.audit.record({ actorUserId: actorId, action: 'admin.fee.created', entityType: 'fee_schedule', entityId: fee.id }); return fee; }); }
  async auditLogs() { const logs = await this.db.auditLog.findMany({ orderBy: { sequence: 'desc' }, take: 250 }); return logs.map((log) => ({ ...log, sequence: log.sequence.toString() })); }
  async setConfig(actorId: string, dto: SetConfigDto) { const config = await this.db.systemConfig.upsert({ where: { key: dto.key }, create: { key: dto.key, encryptedValue: this.encryption.encryptJson(dto.value), description: dto.description, updatedById: actorId }, update: { encryptedValue: this.encryption.encryptJson(dto.value), description: dto.description, updatedById: actorId } }); await this.audit.record({ actorUserId: actorId, action: 'admin.config.updated', entityType: 'system_config', entityId: dto.key }); return { key: config.key, description: config.description, updatedAt: config.updatedAt }; }
  async report() { const [customers, activeAccounts, transferVolume, openAlerts, pendingKyc] = await Promise.all([this.db.user.count(), this.db.account.count({ where: { status: 'ACTIVE' } }), this.db.transfer.aggregate({ where: { status: TransferStatus.COMPLETED }, _sum: { amount: true }, _count: true }), this.db.riskAlert.count({ where: { status: { in: [RiskAlertStatus.OPEN, RiskAlertStatus.INVESTIGATING] } } }), this.db.kycProfile.count({ where: { status: { in: [KycStatus.SUBMITTED, KycStatus.IN_REVIEW] } } })]); return { customers, activeAccounts, completedTransfers: transferVolume._count, transferVolume: transferVolume._sum.amount?.toFixed(2) ?? '0.00', openAlerts, pendingKyc }; }
}
